#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 19 13:00:26 2018

@author: carly
"""

##Part 2 -- APIs ##

import csv
import json
import requests

# REVIEW
# ============================
host = 'http://api.datausa.io/api/'
# https://github.com/DataUSA/datausa-api/wiki/DataAPI

# ACCESS
# ============================
# build api GET request
required_params = "?show=geo&sumlevel=state"
optional_params = "&year=2014"
columns = "&required=age,pop,income"
url = host + required_params + optional_params + columns

print(url)

# check the HTTP response code
response = requests.request('GET', url)
print(response)


# PARSE
# ============================
# parse the JSON data into a python dictionary
degrees = response.json()


# TRANSFORM
# ============================
# display the result in an easy-to-read format
print(json.dumps(degrees, indent = 4, sort_keys = True))
data = [dict(zip(degrees["headers"], d)) for d in degrees["data"]]

# STORE
# ============================

fieldnames = degrees["headers"]

# save data to a csv file
with open("ACS_demoinfo.csv", "w") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames)
    writer.writeheader()
    for row in data:
        writer.writerow(row)
